apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=payments-db-service;Database=paymentsdb;Username=postgres;Password=postgres"
  Jwt__Key: "CHAVE_SUPER_SECRETA_MIN_32_CHARS!!"
  RabbitMQ__Password: "guest"
